databases:
  - name: kit-app-db
    databaseName: kit_app
    user: kit_app
    plan: free

services:
  - type: web
    name: kit-app-api
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kit-app-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.4

